name: Deploy Next.js via Git Pull

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
      - name: Pull branch
        script: |
          echo "ğŸ“¥ Pull latest changes..."

          cd /var/www/adminpersonal.bellukstudio.my.id
          git pull origin main
      - name: Build Docker image
        script: |
          echo "ğŸ³ Build Docker image..."
          docker build -t adminpersonal .
      - name: Stop and remove old container
        script: |
          echo "ğŸ§¼ Stop and remove old container..."
          docker stop adminpersonal || true
          docker rm adminpersonal || true
      - name: Run new container
        script: |
          
          echo "ğŸš€ Run new container..."
          docker run -d --name adminpersonal -p 3002:3002 adminpersonal
